
/**
 * This function is part of the forwarding from signUp to login.
 * If the forwarding was successful, a message appears which is generated by a query parameter.
 * 
 */
function callStatusofSignUp() {
    const signUpStatus = localStorage.getItem('signUpStatus');
    const urlParams = new URLSearchParams(window.location.search);
    const msg = urlParams.get('msg');
    const msgBox = document.getElementById('msgBox');

    if (signUpStatus === 'completed' && msg) {
        const msgSpan = document.createElement('span');
        msgSpan.innerHTML = msg;
        msgSpan.classList.add('successfullyBtn');
        msgBox.appendChild(msgSpan);
        localStorage.removeItem('signUpStatus');
    } else {
        msgBox.style.display = 'none';
    }
}


function checkIfRememberedData() {
    if (localStorage.getItem('email')) {
        let rememberedEmail = localStorage.getItem('email');
        let rememberedPassword = localStorage.getItem('password');

        let emailInput = document.getElementById('email');
        let passwordInput = document.getElementById('password');

        emailInput.value = rememberedEmail;
        passwordInput.value = rememberedPassword;

        disableLogInButton();
    }
}


async function login() {
    let email = document.getElementById('email');
    let password = document.getElementById('password');
    let currentUser = users.find(u => u.email == email.value && u.password == password.value);
    if (currentUser) {
        loggedInEmail = currentUser.email;
        await setItem('loggedInEmail', loggedInEmail);
        window.location.href = './summary.html';
        checkStatusofCheckBox();
        clearLogIn();
    } else {
        displayErrorMessage('wrong e-mail or password', email);
        displayErrorMessage('wrong e-mail or password', password);
    }
}

function disableLogInButton() {
    let emailInput = document.getElementById('email');
    let passwordInput = document.getElementById('password');
    const LogInButton = document.getElementById('LogInButton');

    const allFieldsFilled = emailInput.value && passwordInput.value;

    if (allFieldsFilled) {
        LogInButton.removeAttribute('disabled');
        LogInButton.classList.remove('if-button-disabled');
        LogInButton.classList.add('btn-db');

    } else {
        LogInButton.setAttribute('disabled', true);
        LogInButton.classList.add('if-button-disabled');
    }
}

function checkStatusofCheckBox() {
    let checkbox = document.getElementById('checkbox');
    if (checkbox.checked) {
        let emailInput = document.getElementById('email');
        let passwordInput = document.getElementById('password');
        localStorage.setItem('email', emailInput.value);
        localStorage.setItem('password', passwordInput.value);
    }
}

async function useGuestLogIn() {
    document.getElementById('email').value = 'guest@account';
    document.getElementById('password').value = 'joinGuest2024';

    const guestUser = users.find(user => user.email === 'guest@account');
    if (guestUser) {
        clearLogIn();
        await setItem('loggedInEmail', loggedInEmail);
        window.location.href = './summary.html';
    }
}

function clearLogIn(){
    document.getElementById('email').value = '';
    document.getElementById('password').value = '';
}


